import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { ArtistCard, EventCard, MerchCard, PlaylistCard, TrackCard } from '../components/cards/Cards';
export { ArtistPage as ArtistProfilePage } from './artist/ArtistPage';
export { ProfilePage } from './profile/ProfilePage';
const seedArtists = [
    { name: 'Luna Costa', town: 'Santurce' },
    { name: 'Mar Azul Colectivo', town: 'MayagÃ¼ez' },
    { name: 'Calle Solar', town: 'Ponce' }
];
export const LandingPage = () => (_jsxs("section", { className: "space-y-10", children: [_jsxs("div", { className: "flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "text-sm font-medium text-zinc-400", children: "Hecho para ti" }), _jsx("h1", { className: "text-4xl font-bold tracking-tight text-white md:text-5xl", children: "Buenas noches" })] }), _jsxs(Link, { to: "/favorites", className: "inline-flex items-center gap-3 self-start rounded-2xl border border-cyan-300/20 bg-cyan-400/10 px-4 py-3 text-sm font-medium text-cyan-100 transition hover:bg-cyan-400/15 hover:text-white", children: [_jsx("span", { className: "inline-flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-300/15 text-cyan-200", children: _jsx("svg", { "aria-hidden": "true", viewBox: "0 0 24 24", className: "h-4 w-4", fill: "currentColor", stroke: "currentColor", strokeWidth: "1.8", strokeLinecap: "round", strokeLinejoin: "round", children: _jsx("path", { d: "M12 20.5c-4.7-3.1-7.8-6-7.8-10.1A4.3 4.3 0 0 1 8.5 6c1.5 0 2.8.7 3.5 1.9A4.14 4.14 0 0 1 15.5 6a4.3 4.3 0 0 1 4.3 4.4c0 4.1-3.1 7-7.8 10.1Z" }) }) }), _jsxs("span", { children: [_jsx("span", { className: "block text-xs uppercase tracking-[0.22em] text-cyan-100/65", children: "Shortcut" }), _jsx("span", { className: "block text-base font-semibold text-white", children: "Tus likes" })] })] })] }), _jsx("section", { className: "grid gap-3 md:grid-cols-2 xl:grid-cols-3", children: [
                { title: 'Mix de madrugada', meta: 'Indie + electronica suave', accent: 'from-fuchsia-500 to-orange-400' },
                { title: 'Radar de Santurce', meta: 'Escena local en movimiento', accent: 'from-cyan-400 to-blue-500' },
                { title: 'Sesion Alt Caribe', meta: 'Seleccion curada', accent: 'from-emerald-400 to-teal-500' },
                { title: 'Nuevos estrenos', meta: 'Lo que acaba de caer', accent: 'from-violet-500 to-indigo-500' },
                { title: 'Shows de la semana', meta: 'En vivo por toda la isla', accent: 'from-amber-300 to-orange-500' },
                { title: 'Merch y vinilos', meta: 'Drops limitados', accent: 'from-zinc-500 to-zinc-800' }
            ].map((item) => (_jsxs("div", { className: "group flex items-center gap-4 overflow-hidden rounded-[20px] bg-[#1b1b1b] transition hover:bg-[#252525]", children: [_jsx("div", { className: `h-20 w-20 shrink-0 bg-gradient-to-br ${item.accent}` }), _jsxs("div", { className: "min-w-0 pr-4", children: [_jsx("p", { className: "truncate text-base font-semibold text-white", children: item.title }), _jsx("p", { className: "mt-1 truncate text-sm text-zinc-400", children: item.meta })] })] }, item.title))) }), _jsxs("section", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-end justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold text-white", children: "Quick picks" }), _jsx("p", { className: "mt-1 text-sm text-zinc-400", children: "Tus accesos rapidos para volver a lo que ya te estaba gustando." })] }), _jsx("button", { className: "text-sm font-medium text-zinc-400 hover:text-white", children: "Ver todo" })] }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-2 xl:grid-cols-4", children: [_jsx(TrackCard, { title: "Brisa en Loiza", artist: "Luna Costa" }), _jsx(PlaylistCard, { title: "Alt Caribe", description: "Curado para descubrir ahora" }), _jsx(TrackCard, { title: "Luces del expreso", artist: "Calle Solar" }), _jsx(PlaylistCard, { title: "Isla en loop", description: "Favoritos para volver a poner" })] })] }), _jsxs("section", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-end justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold text-white", children: "Artistas destacados" }), _jsx("p", { className: "mt-1 text-sm text-zinc-400", children: "Voces y proyectos que estan empujando la escena local." })] }), _jsx("button", { className: "text-sm font-medium text-zinc-400 hover:text-white", children: "Ver todo" })] }), _jsx("div", { className: "grid gap-4 md:grid-cols-3", children: seedArtists.map((a) => (_jsx(ArtistCard, { ...a }, a.name))) })] }), _jsxs("section", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-end justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold text-white", children: "Nuevos drops" }), _jsx("p", { className: "mt-1 text-sm text-zinc-400", children: "Estrenos, playlists y fechas para seguir explorando sin salir de portada." })] }), _jsx("button", { className: "text-sm font-medium text-zinc-400 hover:text-white", children: "Ver todo" })] }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-2 xl:grid-cols-4", children: [_jsx(TrackCard, { title: "Postales del Oeste", artist: "Mar Azul Colectivo" }), _jsx(TrackCard, { title: "Cenizas del mar", artist: "Luna Costa" }), _jsx(PlaylistCard, { title: "Descubrimiento boricua", description: "Selecciones frescas para la semana" }), _jsx(EventCard, { title: "Sesion de estreno en vivo", venue: "La Respuesta" })] })] })] }));
export const DiscoverPage = () => (_jsxs("section", { className: "space-y-6", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "Descubrimiento" }), _jsxs("div", { className: "grid gap-4 md:grid-cols-2 lg:grid-cols-4", children: [_jsx(TrackCard, { title: "Brisa en Loiza", artist: "Luna Costa" }), _jsx(TrackCard, { title: "Noche en Rio Piedras", artist: "Calle Solar" }), _jsx(PlaylistCard, { title: "Indie Boricua", description: "Seleccion editorial" }), _jsx(EventCard, { title: "En vivo en Santurce", venue: "La Respuesta" })] })] }));
export const AuthPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "Login / Signup" }), _jsx("p", { className: "text-zinc-400", children: "JWT + refresh token flow scaffolded." })] });
export const ArtistOnboardingPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "Onboarding Artista" }), _jsx("p", { className: "text-zinc-400", children: "Sube perfil, town, bio y enlaces sociales." })] });
export const VerificationPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "Verificacion de artista" }), _jsx("p", { className: "text-zinc-400", children: "ID + selfie + confirmacion de derechos." })] });
export const ArtistDashboardPage = () => _jsxs("section", { className: "grid gap-4 md:grid-cols-4", children: [_jsx("div", { className: "card", children: "Ingresos estimados" }), _jsx("div", { className: "card", children: "Top tracks" }), _jsx("div", { className: "card", children: "Merch clicks" }), _jsx("div", { className: "card", children: "Ticket clicks" })] });
export const UploadTrackPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl", children: "Upload Track" }), _jsx("p", { className: "text-zinc-400", children: "Presigned URL + procesamiento FFmpeg job." })] });
export const TrackDetailPage = () => _jsx("section", { className: "space-y-4", children: _jsxs("div", { className: "card", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "Brisa en Loiza" }), _jsx("p", { className: "text-zinc-400", children: "Waveform, comentarios, likes, report infringement." })] }) });
export const PlaylistsPage = () => _jsx("section", { className: "grid gap-4 md:grid-cols-3", children: ['Indie Boricua', 'Trap y Calle', 'Alt Caribe', 'Rock Isleno', 'Nuevas Voces', 'En Vivo Esta Semana'].map((p) => _jsx(PlaylistCard, { title: p, description: "Curated" }, p)) });
export const PlaylistDetailPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl", children: "Playlist Detail" }), _jsx("p", { className: "text-zinc-400", children: "Track list + curator + mood tags." })] });
export const ReleasesPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl", children: "Upcoming Releases" }), _jsx("p", { className: "text-zinc-400", children: "Countdown + notify me scaffold." })] });
export const ShowsPage = () => _jsxs("section", { className: "grid gap-4 md:grid-cols-2", children: [_jsx(EventCard, { title: "Noches en La Respuesta", venue: "Santurce" }), _jsx(EventCard, { title: "Atardecer en Ponce", venue: "Ponce" })] });
export const MerchPage = () => _jsxs("section", { className: "grid gap-4 md:grid-cols-3", children: [_jsx(MerchCard, { title: "Camiseta Brisa Tour", price: "$30" }), _jsx(MerchCard, { title: "Vinilo Alt Caribe", price: "$40" })] });
export const AdminDashboardPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl", children: "Admin Dashboard" }), _jsx("p", { className: "text-zinc-400", children: "Verification queue, takedowns, feature controls." })] });
export const ModerationPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl", children: "Moderation / Reports" }), _jsx("p", { className: "text-zinc-400", children: "Infringement queue + strike issuance." })] });
export const SettingsPage = () => _jsxs("section", { className: "card", children: [_jsx("h2", { className: "text-2xl", children: "Settings & Account" }), _jsx("p", { className: "text-zinc-400", children: "Profile, security, notifications placeholders." })] });
